### ISSUE TITLE
wxPython4 compability

### ISSUE THREAD

**Issue by larry801** [dictationbridge/dictationbridge-nvda#24]
When use this in alpha build of nvda. An error occured while exiting.
Here is the log.
ERROR - globalPluginHandler.terminate (21:23:47.556):
Error terminating global plugin <globalPlugins.dictation.GlobalPlugin object at 0x04CF1910>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 40, in terminate
  File "C:\Users\John\AppData\Roaming\nvda\addons\DictationBridge\globalPlugins\dictation\__init__.py", line 601, in terminate
  File "C:\Users\John\AppData\Roaming\nvda\addons\DictationBridge\globalPlugins\dictation\__init__.py", line 365, in terminate
AttributeError: 'module' object has no attribute 'PyDeadObjectError'

Please see this link for more information.

https://docs.wxpython.org/MigrationGuide.html#wx-pydeadobjecterror-runtimeerror

**Comment by derekriemer** [comment]
@josephsl we'll need to update this.

**Comment by josephsl** [comment]
Hi,

One way to make the add-on compatible with past and future NVDA releases is catching all exceptions. Although the stable release won't play a tone, it is still important that we fix this by Monday at the latest.

Thanks.

**Comment by josephsl** [comment]
Hi,

I recommend an official emergency patch to go live within 48 hours of NVDA 2018.3 stable release.
