### ISSUE TITLE
NVDA does not reliably echo back dictated text when composing a tweet in Chicken Nugget

### ISSUE THREAD

**Issue by patjk89** [dictationbridge/dictationbridge-nvda#9]
when dictating a tweet in Chicken Nugget, NVDA does not always read back what is dictated. This stopped when I had to restart the screenreader. It was originally working, but after restarting the screenreader, text was not echoed back.

I checked in Notepad, and was able to hear dictation fine. I've tried restarting Dragon as well as NVDA to see if I can't get dictation to work again in nugget,but no luck.
[nvda.txt](https://github.com/dictationbridge/dictationbridge-nvda/files/798376/nvda.txt)

**Comment by derekriemer** [comment]
@mwcampbell do you know what type of edit control is used here?

**Comment by patjk89** [comment]
That issue was using an old build, I have an encountered this bug sense. It was when we were having echo back issues.
